### ISSUE TITLE
Misspellings in QLAD-5

### ISSUE THREAD

**Issue by hamidzafar** [ag-sc/QALD#14]
In ag-sc/QALD/master/5/data/qald-5_train.json, all the URI which has two same letters like "ke**nn**edy" or "employ**ee**s" are saved as "ke**n**edy" or "employ**e**s".

Cheers,
Hamid

**Comment by RicardoUsbeck** [comment]
Could you please fork the repository, fix the spelling mistakes and make a pull request?

**Comment by RicardoUsbeck** [comment]
Hi Hamid, can you do the pull fix please?

**Comment by hamidzafar** [comment]
Sure. In a few days.

**Comment by RicardoUsbeck** [comment]
Thank you in advance!

**Comment by RicardoUsbeck** [comment]
Thank you so much!
