### ISSUE TITLE
Is your Wikidata dataset the same as the one in metaphacts docker ?

### ISSUE THREAD

**Issue by danbri** [ag-sc/QALD#15]
Looking at the qald / wikidata dumps in https://hub.docker.com/r/metaphacts/wikidata-qald-7/ and trying to understand where it came from, I found your https://github.com/ag-sc/QALD/tree/master/7 ... are you the original source of this RDF representation of Wikidata?  I had originally thought it a complete Wikidata dump, but maybe it is your Q/A-oriented representation? Having found https://project-hobbit.eu/challenges/qald2017/qald2017-challenge-tasks/ I guess so...

/cc @vrandezo

**Comment by RicardoUsbeck** [comment]
Hi, it was indeed created by metaphacts. Let me point the folks from metaphacts to that issue.

**Comment by andriy-nikolov** [comment]
Hi, the https://hub.docker.com/r/metaphacts/wikidata-qald-7/ docker image should be used with a Blazegraph journal containing the Wikidata RDF representation. The canonical one to be used for the QALD-7 challenge is available on http://hobbitdata.informatik.uni-leipzig.de/qald7/wikidata-en/ . It contains the Wikidata dumps from a year ago (Jan 2017) taken from here https://dumps.wikimedia.org/wikidatawiki/entities/.

**Comment by RicardoUsbeck** [comment]
Can this issue be closed? @danbri

**Comment by danbri** [comment]
yup, thanks

**Comment by RicardoUsbeck** [comment]
Thank you!
