### ISSUE TITLE
ungrammatical PT questions 

### ISSUE THREAD

**Issue by arademaker** [ag-sc/QALD#22]
In the training dataset (version 9), browsing the Portuguese questions, I saw many ungrammatical and unnatural question such as:

1. "Quem desenvolvido Skype? "
2. "Lista todos jogos de tabuleiro de GMT. "

How the text of the questions were generated?

**Comment by RicardoUsbeck** [comment]
Hi, 
thanks for using QALD. We did an auto-translate and had each question checked by two native speakers actually...If you find errors,  and have time to correct them,  I would appreciate a pull request.

**Comment by RicardoUsbeck** [comment]
Dear @arademaker , did you consider a pull request or can I close this issue for now?

**Comment by arademaker** [comment]
Since my last PR was merged, I was waiting for @DiegoMoussallem changes (see https://github.com/ag-sc/QALD/pull/23#issuecomment-641326673). Is it still relevant to improve the data?

**Comment by arademaker** [comment]
BTW, @RicardoUsbeck do you know if the PT data is related to the work reported in https://link.springer.com/chapter/10.1007/978-3-030-41505-1_21?

**Comment by RicardoUsbeck** [comment]
Hi! I have no idea whether it is related or not. Maybe @DiegoMoussallem knows more since he is also a co-maintainer of that DBpedia I believe

**Comment by DiegoMoussallem** [comment]
Hi @arademaker I am so sorry, I went through some complicated things recently and I totally forgot to upload the corrections from one linguist student in Brazil. I plan to do it during the week. 

Regarding the paper that you pasted here, I couldn't find the full version but as far as I understood by the abstract they created a second corpus based on the DBpedia PT. 

Best,

**Comment by DiegoMoussallem** [comment]
@arademaker I couldn't convert the translations created by one of our master students, Barbara, at UFMG yet. I would like to ask you if you could have a look and see if you agree with all of them, before committing them in the repo.  

https://docs.google.com/spreadsheets/d/1NMo4bS49eseQt47MH4cA5GoajZySt2gNOzmO1eoOS3I/edit#gid=550865483

**Comment by arademaker** [comment]
@DiegoMoussallem , how do you want me to mark the changes? What about general guidelines? For example

> Give me all actors starring in Last Action Hero.

Should we translate titles of movies?

**Comment by arademaker** [comment]
Instead of working on the spreadsheet, I would prefer you to commit what you have and I can later inspect the data here and make PRs as needed.

**Comment by arademaker** [comment]
Hi all, no updates here... @DiegoMoussallem , can you commit the changes you have in this repo so I can revise and make PR directly?

**Comment by RicardoUsbeck** [comment]
Any updates @DiegoMoussallem ?

**Comment by DiegoMoussallem** [comment]
@RicardoUsbeck, @nikit91 will take care of it.

**Comment by RicardoUsbeck** [comment]
Cannot assign it

**Comment by nikit91** [comment]
> Cannot assign it

I guess its because I am not a collaborator for this repo. I can just fork it and raise a PR from there :)

**Comment by arademaker** [comment]
Can someone summarize the situation ? I remember that i made a PR and I was waiting some changers that @DiegoMoussallem said he will make. I still think that many Portugues questions can be improved.

**Comment by RicardoUsbeck** [comment]
Nikit is currently processing the file from Diego to do the pull request, if I got it correctly.

**Comment by nikit91** [comment]
@RicardoUsbeck I have a question regarding the json formatting. Could you please share the name of the library and the parameters you use to pretty print your json?

I need this information to preserve your current formatting :)

**Comment by RicardoUsbeck** [comment]
Hi, I guess this came from the NLIWOD Java Apache Jena-based lib

**Comment by DiegoMoussallem** [comment]
thank you @nikit91 , I really appreciated it.

**Comment by RicardoUsbeck** [comment]
Update in https://github.com/ag-sc/QALD/pull/29 and one more update to come

**Comment by RicardoUsbeck** [comment]
Ping?

**Comment by arademaker** [comment]
Given https://github.com/ag-sc/QALD/pull/29#issuecomment-1209813487

now I am finishing additional fixes the PT sentences

**Comment by arademaker** [comment]
I will try to make a PR until the end of the week
